{
 "title": "SBMS",
 "tags": [
  "sbms",
  "sbms0",
  "solar",
  "electrodacus",
  "battery"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "PV Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" * \"PV Total Current\" / 120 FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Cell1",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 1\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell2",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 2\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell3",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 3\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell4",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 4\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell5",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 5\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell6",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 6\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell7",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 7\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell8",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 8\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Cell Delta",
   "type": "stat",
   "description": "Difference between highest and lowest cell voltages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Cell Delta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Time of last data point",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 8 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a')",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "alias": "Load",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"PV Total Current\")-last(\"Battery Current\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Battery Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "PV Current",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"PV Total Current\")-last(\"Battery Current\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Battery Current",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"PV Total Current\")-last(\"External Load\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Monitor Flags",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 16 },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Monitor Flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Internal Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 23 },
   "targets": [
    {
     "alias": "Internal Temperature",
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Internal Temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Batt Volt",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"Battery Voltage\") FROM \"SBMS_Metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "SOC",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"Battery Voltage\") FROM \"SBMS_Metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "PV Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "PV Current",
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  }
 ]
}